### PR TITLE
NodeUtils: allow YAML list to declare node groups

### PR DESCRIPTION
**Pull request by griznog**
Allow the use of YAML list syntax when defining node groups.

### CODE REVIEW

**Comment by degremont** [comment]
Thanks for the changes. They looks good! However, when I was talking about the commit message, I was really talking about the commit message of the unique commit you should have in this branch.
Could you squash all your 4 commits together in 1 and update the commit message as explained previously?

**Comment by griznog** [comment]
Clearly I'm lost with the git squash part of this, I don't understand why I wound up with the second merge commit? Lot's of "first time doing X" for me in this process, thanks for being patient.

**Comment by degremont** [comment]
Thanks @griznog , I managed the squash things. Thanks for your patch!
If you want to know more about squashing, for next time ;) : https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by griznog** [comment]
> Hey thanks @griznog! Getting ready for your cluster of tractors? ;-)
> We'll be able to squash the commits for you when merging, no worries.

I'm hoping to keep my squash in the garden :)

**Pull request merged**
