### PR TITLE
Engine: declared bracket symbols as attributes of the ParsingEngine

### PR DESCRIPTION
**Pull request by bougetq**
Needed to easily change the patterns ClusterShell.NodeSet parses and
thus use it in pre-existing project where usual patterns are already
meaningful.

### CODE REVIEW

**Comment by degremont** [comment]
typo in commit title (attibute -> attribute)

**Comment by bougetq** [comment]
Sorry, I corrected it.

**Comment by bougetq** [comment]
Also corrected the alignment in the declaration of BRACKETS

**Comment by degremont** [comment]
Yes please. Did you see https://review.gerrithub.io/#/c/240611/ ?

**Comment by bougetq** [comment]
I just did, thank you for the review. I am making the changes.

**Pull request merged**
